[package]
name = "cminus"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = { version = "2.1", features = [ "pretty-print" ] }
pest_derive = "2.1"
inkwell = { version = "0.1.0-beta.3", features = ["llvm10-0"]}
