newline_style = "unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Unstable features below
unstable_features = true
version = "Two"
comment_width = 90
max_width = 90
error_on_line_overflow = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
use_small_heuristics = "Max"
wrap_comments = true
